Repository Sprint3-6/yeogiya, pull requests merged in 2024-04, with the labels that each got.

#12 [Refactor] Prettier 기본값 설정 제거 및 코드에 Prettier 적용 / 로고 디자인 변경 / 버튼 공통 컴포넌트 추가
  .prettierrc
  index.html
  public/assets/logos/logo-big.svg
  public/assets/logos/logo-small.svg
  src/components/Button/index.tsx
  src/components/Button/style.scss
  src/components/Button/types/buttonType.ts
  src/components/Footer/index.tsx
  src/components/Footer/style.scss
  src/components/Header/index.tsx
  src/routes/routes.tsx
  vite.config.ts
Labels: 공통 컴포넌트

#17 [Feat] axios 인스턴스, 인터셉터 구현
  .husky/pre-commit
  README.md
  package-lock.json
  package.json
  src/api/activitiesApi.ts
  src/api/authApi.ts
  src/api/constants/url.ts
  src/api/instance/defaultInstance.ts
  src/api/types/activities.ts
  src/api/types/auth.ts
Labels: 공통 컴포넌트

#20 [Feat] modal 구현, instance 수정
  src/api/instance/defaultInstance.ts
  src/components/modal/useModal.scss
  src/components/modal/useModal.tsx
Labels: 공통 컴포넌트

#21 [Feat] 로딩 페이지, 404 에러 페이지 구현 및 커밋 설정 변경
  .editorconfig
  .gitattributes
  favicon.svg
  index.html
  package.json
  public/assets/icons/icon-loading.svg
  public/assets/logos/logo-icon.svg
  public/assets/logos/logo-notFound.svg
  src/pages/Loading/index.tsx
  src/pages/Loading/style.scss
  src/pages/NotFound/index.tsx
  src/pages/NotFound/style.scss
  src/routes/routes.tsx
Labels: 공통 컴포넌트

#24 [Feat] 토스트 구현, BASE_URL 수정
  index.html
  public/assets/images/toast-error.png
  public/assets/images/toast-success.png
  public/assets/images/toast-warning.png
  src/components/ToastContainer/index.tsx
  src/components/ToastContainer/style.scss
  src/components/ToastContainer/types/toastType.ts
  src/pages/ActivityDetails/index.tsx
  src/pages/ActivityDetails/style.scss
  src/pages/Main/index.tsx
  src/styles/_base.scss
  src/utils/toast.tsx
Labels: 공통 컴포넌트

#28 [Design] 클래스명 변경
  public/assets/images/background-emptyRoom.jpg
  src/components/Button/style.scss
  src/pages/Loading/index.tsx
  src/pages/Loading/style.scss
  src/pages/NotFound/index.tsx
  src/pages/NotFound/style.scss
Labels: 공통 컴포넌트

#33 [Feat] MyManagement페이지 구현, css추가
  public/assets/icons/icon-meatball.svg
  public/assets/icons/icon-star.svg
  src/components/Footer/style.scss
  src/pages/ActivityManagement/ActivityManagement.scss
  src/pages/ActivityManagement/components/MyActivityCard/MyActivityCard.scss
  src/pages/ActivityManagement/components/MyActivityHeader/MyActivityHeader.scss
  src/pages/MySpaceManagement/MySpaceManagement.scss
  src/pages/MySpaceManagement/components/MyActivityCard/MyActivityCard.scss
  src/pages/MySpaceManagement/components/MyActivityCard/index.tsx
  src/pages/MySpaceManagement/components/MyActivityHeader/MyActivityHeader.scss
  src/pages/MySpaceManagement/components/MyActivityHeader/index.tsx
  src/pages/MySpaceManagement/components/MyActivityList/MyActivityList.scss
  src/pages/MySpaceManagement/components/MyActivityList/index.tsx
  src/pages/MySpaceManagement/index.tsx
  src/pages/MySpaceManagement/types/index.ts
Labels: 내 공간 관리 페이지

#35 [Chore] 임시로그인버튼 리팩터링
  src/App.tsx
  src/api/getMyInfo.ts
  src/components/temp/index.tsx
  src/components/temp/style.scss
  src/pages/ActivityDetails/index.tsx
  src/pages/Main/index.tsx
  src/redux/myInfoSlice.ts
  src/redux/store/store.ts
Labels: 메인 페이지

#36 [Docs] 체험 => 공간
  src/pages/Main/index.tsx
  src/pages/SpaceDetails/index.tsx
  src/pages/SpaceDetails/style.scss
  src/routes/routes.tsx
Labels: 공통 컴포넌트

#37 [Rename] url주소 및 폴더이름 수정
  src/api/instance/defaultInstance.ts
  src/pages/AddSpace/index.tsx
  src/pages/EditSpace/index.tsx
  src/pages/Main/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyReservation/index.tsx
  src/routes/routes.tsx
Labels: 공통 컴포넌트

#38 [Design] 로딩페이지 디자인 변경
  public/assets/icons/icon-loading.svg
  src/pages/Loading/style.scss
Labels: 공통 컴포넌트

#40 [Feat] 네비게이션 바 구현
  public/assets/icons/icon-closed.svg
  public/assets/icons/icon-notification.svg
  public/assets/icons/icon-vector.svg
  public/assets/images/profile-default.png
  src/api/getMyNotifications.ts
  src/api/types/notifications.ts
  src/components/Header/components/HeaderButtons.tsx
  src/components/Header/components/HeaderDropdown.tsx
  src/components/Header/components/headerButton.scss
  src/components/Header/components/headerDropdown.scss
  src/components/Header/index.tsx
  src/components/Header/style.scss
  src/components/MyNotifications/components/Notification.tsx
  src/components/MyNotifications/index.tsx
  src/components/MyNotifications/style.scss
  src/pages/Main/index.tsx
Labels: 공통 컴포넌트

#45 [Design] 공통 스타일 설정 변경
  src/styles/_base.scss
Labels: 공통 컴포넌트

#44 [Feat] AddSpace 페이지 부분 완성 및 css
  package-lock.json
  package.json
  public/assets/icons/icon-image-delete.svg
  public/assets/images/add-img-button.png
  src/api/types/activities.ts
  src/pages/AddSpace/comnponents/AddPlaceForm/index.tsx
  src/pages/AddSpace/comnponents/AddPlaceForm/style.scss
  src/pages/AddSpace/comnponents/DescriptionInput/index.tsx
  src/pages/AddSpace/comnponents/ImageUploader/index.tsx
  src/pages/AddSpace/comnponents/ImageUploader/style.scss
  src/pages/AddSpace/comnponents/KakaoPostSearch/index.tsx
  src/pages/AddSpace/comnponents/PriceInput/index.tsx
  src/pages/AddSpace/comnponents/TitleInput/index.tsx
  src/pages/AddSpace/index.tsx
  src/pages/AddSpace/types/index.tsx
  src/pages/MySpaceManagement/components/MyActivityCard/index.tsx
  src/pages/MySpaceManagement/components/MyActivityHeader/index.tsx
  src/pages/MySpaceManagement/components/MySpaceCard/index.tsx
  src/pages/MySpaceManagement/components/MySpaceCard/style.scss
  src/pages/MySpaceManagement/components/MySpaceHeader/index.tsx
  src/pages/MySpaceManagement/components/MySpaceHeader/style.scss
  src/pages/MySpaceManagement/components/MySpaceList/index.tsx
  src/pages/MySpaceManagement/components/MySpaceList/style.scss
  src/pages/MySpaceManagement/index.tsx
  src/pages/MySpaceManagement/style.scss
  src/pages/MySpaceManagement/types/index.ts
Labels: 내 공간 등록 페이지

#47 [Design] 전체 페이지 높이 및 스크롤바 변경
  src/App.tsx
  src/hooks/useModal/useModal.tsx
  src/routes/layout/index.tsx
  src/routes/layout/style.scss
  src/routes/routes.tsx
  src/styles/_base.scss
Labels: 공통 컴포넌트

#48 [Chore] 헤더 리덕스툴킷 관련 코드수정
  .env
  .eslintrc.cjs
  index.html
  package-lock.json
  package.json
  src/api/getSpaceDetail.ts
  src/components/Header/components/HeaderButtons.tsx
  src/components/KakaoMap/index.tsx
  src/components/KakaoMap/style.scss
  src/pages/Main/index.tsx
  src/pages/SpaceDetails/Types/DetailType.ts
  src/pages/SpaceDetails/index.tsx
  src/pages/SpaceDetails/style.scss
  src/redux/myInfoSlice.ts
  src/redux/store/store.ts
  src/utils/categoryFilter.tsx
  vite.config.ts
Labels: 공통 컴포넌트, 공간 상세 페이지

#50 [Feat] 드롭다운 구현
  package-lock.json
  src/components/Dropdown/index.tsx
  src/components/Dropdown/style.scss
  src/pages/SignIn/index.tsx
  src/pages/SignIn/style.scss
Labels: 공통 컴포넌트

#52 [Refactor] 드롭다운 리팩토링 (속성값 수정 및 css 직접 적용으로 변경)
  package-lock.json
  src/components/Dropdown/index.tsx
  src/components/Dropdown/style.scss
Labels: 공통 컴포넌트

#55 [Feat] 체험후기 부분까지 구현
  .env
  index.html
  src/api/getSpaceDetail.ts
  src/api/getUserReview.ts
  src/components/KakaoMap/index.tsx
  src/components/KakaoMap/style.scss
  src/pages/SpaceDetails/Types/DetailTypes.ts
  src/pages/SpaceDetails/index.tsx
  src/pages/SpaceDetails/style.scss
  src/utils/ratingFilter.tsx
Labels: 공간 상세 페이지

#54 [Feat] 마이페이지 사이드바 레이아웃 구현
  src/components/Dropdown/style.scss
  src/components/MypageSidebar/index.tsx
  src/components/MypageSidebar/style.scss
  src/routes/mypagelayout/index.tsx
  src/routes/mypagelayout/style.scss
  src/routes/routes.tsx
Labels: 공통 컴포넌트

#57 [Refactor] 드롭다운 이벤트 버블링 현상 및 함수 파라미터 값 변경
  src/components/Dropdown/index.tsx
Labels: 공통 컴포넌트

#58 [Feat] 공통 캘린더 구현
  package-lock.json
  package.json
  public/assets/icons/icon-left.svg
  public/assets/icons/icon-right.svg
  src/components/Calendar/components/CalendarCells.tsx
  src/components/Calendar/components/CalendarHeader.tsx
  src/components/Calendar/components/calendarCells.scss
  src/components/Calendar/components/calendarHeader.scss
  src/components/Calendar/index.tsx
  src/components/Calendar/style.scss
  src/components/Calendar/types/calendarType.d.ts
  src/utils/calendarUtils.ts
Labels: 공통 컴포넌트

#59 [Feat] 리덕스-퍼시스트로 새로고침 해도 상태보존
  package-lock.json
  package.json
  src/App.tsx
  src/api/deleteMySpace.ts
  src/api/getMyInfo.ts
  src/api/types/axiosErrorType.ts
  src/components/temp/index.tsx
  src/components/temp/style.scss
  src/pages/SpaceDetails/Components/DeleteModal/index.tsx
  src/pages/SpaceDetails/Components/DeleteModal/style.scss
  src/pages/SpaceDetails/Types/DetailTypes.ts
  src/pages/SpaceDetails/index.tsx
  src/pages/SpaceDetails/style.scss
  src/redux/store/store.ts
Labels: 공통 컴포넌트, 공간 상세 페이지

#66 [Refactor] `useCalendar` 추가 및 Redux store 공통 사용 경로로 수정
  src/App.tsx
  src/components/Button/style.scss
  src/components/Calendar/components/CalendarHeader.tsx
  src/components/Calendar/hooks/useCalendar.tsx
  src/components/Calendar/index.tsx
  src/components/Calendar/types/calendarType.d.ts
  src/components/Header/components/HeaderButtons.tsx
  src/components/Header/index.tsx
  src/components/MyNotifications/index.tsx
  src/pages/AddSpace/comnponents/Schdules/DateInput/index.tsx
  src/pages/Loading/index.tsx
  src/pages/NotFound/index.tsx
  src/pages/SpaceDetails/Components/DeleteModal/style.scss
  src/pages/SpaceDetails/index.tsx
  src/redux/store/index.ts
  src/styles/_base.scss
  vite.config.ts
Labels: 공통 컴포넌트
