Repository Sprint3-6/yeogiya, pull requests merged in 2024-05, with the labels that each got.

#68 [Design] input에 기본 폰트 설정 추가
  src/styles/_base.scss
Labels: 공통 컴포넌트

#69 [Refactor] 버튼컴포넌트 extends 수정 및 내 공간 등록 css 추가
  src/components/Button/types/buttonType.ts
  src/pages/AddSpace/comnponents/CategoryDropdown/index.tsx
  src/pages/AddSpace/comnponents/Schdules/DateInput/index.tsx
  src/pages/AddSpace/comnponents/Schdules/index.tsx
  src/pages/AddSpace/comnponents/Schdules/style.scss
Labels: 공통 컴포넌트, 내 공간 수정 페이지, 내 공간 등록 페이지

#70 [Feat] 캘린더로 예약신청 구현
  public/assets/icons/icon-minus.svg
  public/assets/icons/icon-plus.svg
  src/api/getOpenedSchedule.ts
  src/api/getSpaceDetail.ts
  src/api/postReservation.ts
  src/api/types/axiosErrorType.ts
  src/components/Calendar/components/CalendarCells.tsx
  src/components/Calendar/types/calendarType.d.ts
  src/components/ToastContainer/style.scss
  src/pages/Main/index.tsx
  src/pages/SpaceDetails/Components/CalendarContainer/index.tsx
  src/pages/SpaceDetails/Types/DetailTypes.ts
  src/pages/SpaceDetails/index.tsx
  src/pages/SpaceDetails/style.scss
Labels: 공간 상세 페이지

#72 [Refactor]: AddSpace, EditSpace, Schedule 유효성 검사 기능 강화 및 기타 작업
  src/pages/AddSpace/comnponents/AddPlaceForm/index.tsx
  src/pages/AddSpace/comnponents/PriceInput/index.tsx
  src/pages/AddSpace/comnponents/Schdules/DateInput/index.tsx
  src/pages/AddSpace/comnponents/Schdules/TimeDropdown/index.tsx
  src/pages/AddSpace/comnponents/Schdules/index.tsx
  src/pages/AddSpace/comnponents/Schdules/style.scss
  src/pages/EditSpace/index.tsx
  src/utils/compareTime.ts
  src/utils/removeCommas.ts
Labels: 내 공간 수정 페이지, 내 공간 등록 페이지

#75 [Feat] 예약 현황 페이지 구현 및 공통 컴포넌트 수정
  src/api/instance/axiosBaseQuery.ts
  src/api/reservationStatusApi.ts
  src/api/types/axiosBase.ts
  src/api/types/reservationStatus.d.ts
  src/components/Calendar/components/CalendarCells.tsx
  src/components/Calendar/components/CalendarHeader.tsx
  src/components/Calendar/components/CalendarReservationChip.tsx
  src/components/Calendar/components/ReservationInformation.tsx
  src/components/Calendar/components/calendarCells.scss
  src/components/Calendar/components/calendarReservationChip.scss
  src/components/Calendar/components/reservationInformation.scss
  src/components/Calendar/types/calendarType.d.ts
  src/components/Dropdown/index.tsx
  src/pages/ErrorModal/index.tsx
  src/pages/ErrorModal/style.scss
  src/pages/Loading/index.tsx
  src/pages/Loading/style.scss
  src/pages/ReservationStatus/index.tsx
  src/pages/ReservationStatus/style.scss
  src/pages/ReservationStatus/types/reservationTypes.d.ts
  src/redux/store/index.ts
  src/utils/calendarUtils.ts
Labels: 공통 컴포넌트, 예약 현황

#77 [Feat] 태블릿,모바일 반응형 구현
  public/assets/icons/icon-left-slider.svg
  public/assets/icons/icon-right-slider.svg
  src/api/postReservation.ts
  src/components/Calendar/components/calendarCells.scss
  src/pages/SpaceDetails/Components/CalendarContainer/index.tsx
  src/pages/SpaceDetails/Components/CalendarContainer/style.scss
  src/pages/SpaceDetails/Components/CalendarTablet(Temp)/index.tsx
  src/pages/SpaceDetails/Types/DetailTypes.ts
  src/pages/SpaceDetails/index.tsx
  src/pages/SpaceDetails/style.scss
  src/utils/ratingFilter.tsx
Labels: 공간 상세 페이지

#78 [Refactor] 로그인 / 회원가입 페이지 구현 1차 완료
  public/assets/icons/icon-eye.svg
  public/assets/icons/icon-list-hover.svg
  public/assets/icons/icon-myinfo-hover.svg
  public/assets/icons/icon-relstatus-hover.svg
  public/assets/icons/icon-setting-hover.svg
  src/api/UsersApi.ts
  src/api/authApi.ts
  src/components/MypageSidebar/components/MypageProfile.tsx
  src/components/MypageSidebar/components/MypageSideList.tsx
  src/components/MypageSidebar/index.tsx
  src/components/MypageSidebar/style.scss
  src/components/UserForm/components/UserInputItem.tsx
  src/components/UserForm/index.tsx
  src/components/UserForm/style.scss
  src/components/UserForm/types/index.ts
  src/pages/MyPage/components/MyPageList.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyPage/style.scss
  src/pages/SignIn/index.tsx
  src/pages/SignUp/index.tsx
Labels: 로그인 페이지, 회원가입 페이지

#80 [Feat] 마이페이지 리다이렉트 기능 및 기타 작업
  src/hooks/useMyActivities/index.ts
  src/pages/AddSpace/comnponents/AddPlaceForm/index.tsx
  src/pages/AddSpace/comnponents/AddPlaceForm/style.scss
  src/pages/EditSpace/index.tsx
  src/pages/EditSpace/styles.scss
  src/pages/MySpaceManagement/components/MySpaceCard/index.tsx
  src/pages/MySpaceManagement/components/MySpaceCard/style.scss
  src/pages/MySpaceManagement/components/MySpaceHeader/index.tsx
  src/pages/MySpaceManagement/components/MySpaceHeader/style.scss
  src/pages/MySpaceManagement/components/MySpaceList/index.tsx
  src/pages/MySpaceManagement/index.tsx
  src/pages/MySpaceManagement/style.scss
  src/routes/mypagelayout/index.tsx
Labels: 기타

#81 [Refactor] instance에 multipart/form-data추가
  src/api/activitiesApi.ts
  src/api/instance/defaultInstance.ts
Labels: 기타

#79 [Fix] 예약현황 페이지에서 id가 없을 때 오류나는 버그 수정 및 예약이 없을 때 예약 없음을 보여주는 화면 추가
  src/pages/ReservationStatus/index.tsx
  src/pages/ReservationStatus/style.scss
Labels: 예약 현황

#85 [Fix] 예약 현황 페이지에서 드롭다운 선택 시 예약 현황 보이도록 수정 등
  src/api/reservationStatusApi.ts
  src/api/types/reservationStatus.d.ts
  src/components/Button/types/buttonType.ts
  src/components/Calendar/components/ReservationInformation.tsx
  src/components/Calendar/components/calendarCells.scss
  src/components/Calendar/components/reservationInformation.scss
  src/hooks/useModal/useModal.scss
  src/pages/ErrorModal/index.tsx
  src/pages/Loading/index.tsx
  src/pages/Loading/types/loadingType.ts
  src/pages/ReservationStatus/index.tsx
Labels: 공통 컴포넌트, 예약 현황

#83 [Feat] 내정보 페이지 및 마이페이지 사이드바 구현 1차
  src/api/UsersApi.ts
  src/api/authApi.ts
  src/api/getMyInfo.ts
  src/components/MypageSidebar/components/MypageProfile.tsx
  src/components/MypageSidebar/components/MypageSideList.tsx
  src/components/MypageSidebar/style.scss
  src/components/UserForm/style.scss
  src/pages/MyPage/components/MyPageList.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyPage/style.scss
  src/pages/MyPage/types/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignIn/style.scss
  src/pages/SignUp/index.tsx
  src/pages/SignUp/style.scss
Labels: 내 정보 페이지, 마이페이지 사이드바

#84 [Feat] 메인페이지 검색 기능 추가
  src/api/constants/categories.ts
  src/api/getSpaces.ts
  src/api/types/activities.ts
  src/components/Header/components/HeaderButtons.tsx
  src/hooks/useDeviceType/useDeviceType.ts
  src/pages/Main/components/SearchBar.tsx
  src/pages/Main/components/SpaceCard.tsx
  src/pages/Main/components/SpaceCardList.tsx
  src/pages/Main/components/searchBar.scss
  src/pages/Main/components/spaceCardList.scss
  src/pages/Main/index.tsx
  src/pages/Main/style.scss
  src/pages/Main/types/spaces-type.ts
  src/pages/MyReservation/index.tsx
  src/utils/categoryFilter.tsx
Labels: 메인 페이지, 예약 내역 페이지

#86 [Feat] 스케줄 중복 시간대 검사 기능 구현 및 기타 작업
  src/api/getSpaceDetail.ts
  src/hooks/useAddPlaceForm/index.ts
  src/hooks/useEditSpaceForm/index.ts
  src/pages/AddSpace/comnponents/AddPlaceForm/index.tsx
  src/pages/AddSpace/comnponents/CategoryDropdown/index.tsx
  src/pages/AddSpace/comnponents/CategoryDropdown/styles.scss
  src/pages/AddSpace/comnponents/Schdules/index.tsx
  src/pages/EditSpace/index.tsx
  src/routes/routes.tsx
  src/routes/signLayout/index.tsx
  src/utils/compareTime.ts
  src/utils/findMissingIds.ts
Labels: 내 공간 관리 페이지, 내 공간 수정 페이지, 내 공간 등록 페이지, 기타

#87 [Fix] type 오류 해결을 위한 옵셔널 추가 및 타입 폴더 이동
  src/api/types/reservationStatus.d.ts
  src/components/Calendar/components/ReservationInformation.tsx
  src/pages/Loading/types/loadingType.ts
Labels: 공통 컴포넌트, 예약 현황

#88 [Chore] 주소 클립보드 복사, 미 로그인 예약클릭시 로그인 하세요
  public/assets/images/copy.png
  src/api/postReservation.ts
  src/pages/SpaceDetails/Components/CalendarContainer/index.tsx
  src/pages/SpaceDetails/index.tsx
  src/pages/SpaceDetails/style.scss
Labels: 공간 상세 페이지

#89 [Fix] Header 버튼 수정 및 메인페이지 조건부 렌더링
  src/components/Footer/style.scss
  src/components/Header/components/HeaderButtons.tsx
  src/pages/Main/components/SpaceCardList.tsx
  src/pages/Main/index.tsx
Labels: 메인 페이지, 공통 컴포넌트

#90 [Fix] 예약 현황 모달 내 예약 내역이 업데이트 될 때마다 캐시를 초기화하도록 수정
  public/assets/icons/icon-top.svg
  src/api/reservationStatusApi.ts
  src/components/Calendar/components/ReservationInformation.tsx
  src/components/Calendar/components/reservationInformation.scss
Labels: 예약 현황

#94 [Design] 삭제 모달, 프로필 이미지 수정 모달 디자인 변경
  src/components/MypageSidebar/components/MypageProfile.tsx
  src/components/MypageSidebar/style.scss
  src/pages/SpaceDetails/Components/DeleteModal/index.tsx
  src/pages/SpaceDetails/Components/DeleteModal/style.scss
Labels: 기타

#92 [Feat] 헤더 드롭다운 구현
  src/components/Dropdown/index.tsx
  src/components/Header/components/HeaderButtons.tsx
  src/components/Header/components/HeaderDropdown.tsx
  src/components/Header/components/headerDropdown.scss
  src/components/MypageSidebar/style.scss
  src/components/UserForm/components/UserInputItem.tsx
  src/components/UserForm/style.scss
  src/pages/SignIn/style.scss
Labels: 공통 컴포넌트

#93 [Feat] 예약내역페이지 및 헤더 알림 모달 구현
  package-lock.json
  package.json
  public/assets/icons/icon-closed-light.svg
  src/api/types/myReservation.ts
  src/api/types/notifications.ts
  src/components/MyNotifications/components/Notification.tsx
  src/components/MyNotifications/components/notification.scss
  src/components/MyNotifications/index.tsx
  src/components/MyNotifications/style.scss
  src/pages/Main/index.tsx
  src/pages/MyReservation/components/MyReservationCard/index.tsx
  src/pages/MyReservation/components/MyReservationCard/style.scss
  src/pages/MyReservation/components/MyReviewContents/index.tsx
  src/pages/MyReservation/components/MyReviewContents/style.scss
  src/pages/MyReservation/components/MyReviewModal/index.tsx
  src/pages/MyReservation/components/MyReviewModal/style.scss
  src/pages/MyReservation/index.tsx
  src/utils/calculateElapsedTime.ts
  src/utils/reservationStatusFilter.ts
Labels: 공통 컴포넌트, 예약 내역 페이지

#95 [Fix] 예약 현황 모달 내 시간 드롭다운 건수 있을 때만 뜨도록 수정, 시간 드롭다운 스크롤 기능 추가
  public/assets/icons/icon-top.gif
  public/assets/icons/icon-top.svg
  src/components/Calendar/components/ReservationInformation.tsx
  src/components/Calendar/components/reservationInformation.scss
Labels: 예약 현황

#99 [Design] map 아이콘 추가
  public/assets/icons/icon-map.svg
Labels: 기타

#100 [Fix] 스케줄을 비교해주는 util함수 수정 및 css 수정
  src/pages/AddSpace/components/AddPlaceForm/index.tsx
  src/pages/AddSpace/components/AddPlaceForm/style.scss
  src/pages/AddSpace/components/Schdules/DateInput/style.scss
  src/pages/AddSpace/components/Schdules/index.tsx
  src/pages/AddSpace/components/Schdules/style.scss
  src/pages/EditSpace/index.tsx
  src/pages/MySpaceManagement/components/MySpaceCard/index.tsx
  src/utils/compareTime.ts
Labels: 내 공간 관리 페이지, 내 공간 수정 페이지, 내 공간 등록 페이지

#101 [Fix] 예약현황 페이지 드롭다운 상태값 수정
  src/api/reservationStatusApi.ts
  src/components/Calendar/components/ReservationInformation.tsx
  src/components/Calendar/components/reservationInformation.scss
  src/components/Dropdown/index.tsx
  src/pages/ReservationStatus/index.tsx
Labels: 예약 현황

#102 [Feat] 로그인 안했을때 예약하면 로그인화면으로 보내버리고 로그인 하면 다시 보던 페이지로
  src/api/postReservation.ts
  src/pages/SignIn/index.tsx
  src/pages/SpaceDetails/Components/CalendarContainer/index.tsx
  src/pages/SpaceDetails/Components/CalendarContainer/style.scss
  src/pages/SpaceDetails/Components/ToLoginModal/index.tsx
  src/pages/SpaceDetails/Components/ToLoginModal/style.scss
  src/pages/SpaceDetails/Types/DetailTypes.ts
  src/pages/SpaceDetails/index.tsx
  src/pages/SpaceDetails/style.scss
Labels: 공간 상세 페이지

#103 [Feat] 예약내역페이지 예약취소 모달 및 헤더 알림, 메인페이지 수정
  package-lock.json
  package.json
  public/assets/icons/icon-check.svg
  src/api/getMyNotifications.ts
  src/components/Button/types/buttonType.ts
  src/components/Footer/style.scss
  src/components/Header/components/HeaderButtons.tsx
  src/components/Header/components/headerButton.scss
  src/components/MyNotifications/components/Notification.tsx
  src/components/MyNotifications/components/notification.scss
  src/components/MyNotifications/index.tsx
  src/components/MyNotifications/style.scss
  src/pages/Main/components/Banner/index.tsx
  src/pages/Main/components/Banner/style.scss
  src/pages/Main/components/HotSpaceCard/index.tsx
  src/pages/Main/components/HotSpaceCard/style.scss
  src/pages/Main/components/HotSpaceCardList/index.tsx
  src/pages/Main/components/HotSpaceCardList/style.scss
  src/pages/Main/components/SearchBar.tsx
  src/pages/Main/components/SpaceCardList.tsx
  src/pages/Main/components/searchBar.scss
  src/pages/Main/components/spaceCard.scss
  src/pages/Main/components/spaceCardList.scss
  src/pages/Main/index.tsx
  src/pages/Main/style.scss
  src/pages/MyReservation/components/CanceledModal/index.tsx
  src/pages/MyReservation/components/CanceledModal/style.scss
  src/pages/MyReservation/components/MyReservationCard/index.tsx
  src/pages/MyReservation/components/MyReservationCard/style.scss
  src/pages/MyReservation/components/MyReviewContents/style.scss
  src/pages/MyReservation/components/MyReviewModal/index.tsx
  src/pages/MyReservation/components/MyReviewModal/style.scss
  src/pages/MyReservation/index.tsx
  src/pages/MyReservation/style.scss
  src/styles/_base.scss
  src/utils/categoryFilter.tsx
Labels: 메인 페이지, 공통 컴포넌트, 예약 내역 페이지

#105 [Feat] 예약현황 모달 내 예약내역 무한스크롤 구현
  src/api/reservationStatusApi.ts
  src/api/types/reservationStatus.d.ts
  src/hooks/useIntersectionObserver/useIntersectionObserver.ts
  src/pages/ReservationStatus/components/ReservationInformation.tsx
  src/pages/ReservationStatus/components/reservationInformation.scss
  src/pages/ReservationStatus/hooks/useReservationInformation.ts
  src/pages/ReservationStatus/index.tsx
  src/pages/ReservationStatus/types/reservationTypes.d.ts
Labels: 공통 컴포넌트, 예약 현황

#107 [Design] 인기 공간, 페이지네이션, 푸터, 알림 모달 수정
  src/components/Footer/style.scss
  src/components/MyNotifications/style.scss
  src/components/Pagination/components/paginationButton.scss
  src/pages/Main/components/HotSpaceCard/style.scss
  src/pages/Main/components/HotSpaceCardList/index.tsx
  src/pages/Main/components/HotSpaceCardList/style.scss
Labels: 메인 페이지, 공통 컴포넌트

#108 [Hotfix] 예약현황 페이지 내 컴포넌트 props 오류 수정
  src/routes/routes.tsx
Labels: 예약 현황

#110 [Chore] 토스트 로직 수정
  index.html
  src/components/ToastContainer/index.tsx
  src/components/ToastContainer/style.scss
  src/components/ToastContainer/types/toastType.ts
  src/pages/SpaceDetails/Components/CalendarContainer/index.tsx
  src/pages/SpaceDetails/Components/CalendarContainer/style.scss
  src/pages/SpaceDetails/style.scss
  src/utils/categoryFilter.ts
  src/utils/handleImageSource.ts
  src/utils/ratingFilter.ts
  src/utils/toast.ts
  src/utils/toast.tsx
Labels: 공통 컴포넌트

#109 [Fix] modal 포탈위치 변경 및 라우터 서스팬스
  index.html
  src/App.tsx
  src/hooks/useModal/useModal.tsx
  src/routes/routes.tsx
Labels: 공통 컴포넌트

#111 [Feat] 예약내역페이지 무한스크롤 추가 및 메인페이지 css 수정
  src/pages/Main/components/HotSpaceCardList/index.tsx
  src/pages/Main/components/HotSpaceCardList/style.scss
  src/pages/Main/components/SearchBar.tsx
  src/pages/Main/components/SpaceCardList.tsx
  src/pages/Main/components/searchBar.scss
  src/pages/Main/components/spaceCard.scss
  src/pages/Main/components/spaceCardList.scss
  src/pages/Main/index.tsx
  src/pages/Main/style.scss
  src/pages/MyReservation/index.tsx
Labels: 메인 페이지, 예약 내역 페이지

#112 [Refactor] useModal 리팩토링
  src/hooks/useModal/useModal.tsx
  src/pages/AddSpace/components/AddPlaceForm/style.scss
  src/pages/AddSpace/components/Schdules/style.scss
  src/pages/EditSpace/styles.scss
  src/pages/SpaceDetails/Components/CalendarContainer/index.tsx
Labels: 기타

#113 [Design] base, mypagelayouy, edit, addspace 등 페이지 css 수정
  src/pages/AddSpace/components/AddPlaceForm/index.tsx
  src/pages/AddSpace/components/AddPlaceForm/style.scss
  src/pages/AddSpace/components/ImageUploader/style.scss
  src/pages/EditSpace/index.tsx
  src/pages/EditSpace/styles.scss
  src/pages/MySpaceManagement/components/MySpaceCard/style.scss
  src/routes/mypagelayout/style.scss
  src/styles/_base.scss
Labels: 내 공간 관리 페이지, 내 공간 수정 페이지, 내 공간 등록 페이지, 기타

#115 [Design] 예약현황 페이지 디자인 수정
  src/components/Calendar/components/calendarCells.scss
  src/components/Calendar/components/calendarReservationChip.scss
  src/components/Calendar/style.scss
  src/components/Header/components/headerDropdown.scss
  src/pages/ReservationStatus/style.scss
  src/styles/_base.scss
Labels: 예약 현황

#116 [Design] 작은 캘린더에 padding 추가
  src/components/Calendar/style.scss
Labels: 공통 컴포넌트

#117 [Design] 예약현황 모달 내 디자인 수정
  src/pages/ReservationStatus/components/ReservationInformation.tsx
  src/pages/ReservationStatus/components/reservationInformation.scss
  src/styles/_base.scss
Labels: 예약 현황

#118 [Design] 현진님의 이미지 업로드 컴포넌트 디자인 수정
  src/pages/AddSpace/components/ImageUploader/style.scss
Labels: 내 공간 수정 페이지, 내 공간 등록 페이지

#119 [Feat] 메인페이지 배너 캐러셀 추가
  public/assets/images/banner-image-party.jpg
  public/assets/images/banner-image-studio.jpg
  public/assets/images/banner-image-wework.jpg
  src/components/Header/components/headerButton.scss
  src/components/Header/style.scss
  src/components/MyNotifications/style.scss
  src/hooks/useBanner/index.ts
  src/pages/Main/components/Banner/index.tsx
  src/pages/Main/components/Banner/style.scss
  src/pages/Main/components/CarouselArrow/index.tsx
  src/pages/Main/components/HotSpaceCardList/index.tsx
  src/pages/Main/components/HotSpaceCardList/style.scss
  src/pages/Main/components/searchBar.scss
  src/pages/Main/components/spaceCard.scss
  src/pages/MyReservation/components/MyReservationCard/style.scss
  src/pages/MyReservation/style.scss
  src/styles/_base.scss
Labels: 메인 페이지, 공통 컴포넌트, 예약 내역 페이지

#120 [Feat] 사진 누르면 크게보기 외
  src/pages/SpaceDetails/Components/BigPictureModal/index.tsx
  src/pages/SpaceDetails/Components/BigPictureModal/style.scss
  src/pages/SpaceDetails/Components/CalendarContainer/style.scss
  src/pages/SpaceDetails/Types/DetailTypes.ts
  src/pages/SpaceDetails/index.tsx
  src/pages/SpaceDetails/style.scss
Labels: 공간 상세 페이지

#121 [Fix] 드롭다운 글자수가 많아지면 ...이 보이도록 수정 및 그걸 위해 드롭다운 컴포넌트에 클래스 추가
  src/components/Dropdown/index.tsx
  src/components/Dropdown/style.scss
  src/pages/AddSpace/components/CategoryDropdown/styles.scss
  src/pages/ReservationStatus/style.scss
Labels: 공통 컴포넌트, 예약 현황

#122 [Fix] 폴더구조 변경 및 콘솔삭제 등등..
  src/api/getMyNotifications.ts
  src/components/Header/components/HeaderButton/index.tsx
  src/components/Header/components/HeaderButton/style.scss
  src/components/Header/components/HeaderDropDown/index.tsx
  src/components/Header/components/HeaderDropDown/style.scss
  src/components/Header/index.tsx
  src/components/Header/style.scss
  src/components/MyNotifications/components/Notification/index.tsx
  src/components/MyNotifications/components/Notification/style.scss
  src/components/MyNotifications/index.tsx
  src/components/MyNotifications/style.scss
  src/components/Pagination/components/ArrowButton/index.tsx
  src/components/Pagination/components/PageButton/index.tsx
  src/components/Pagination/components/PageButton/style.scss
  src/components/Pagination/index.tsx
  src/hooks/usePaginator/index.ts
  src/pages/Main/components/Banner/index.tsx
  src/pages/Main/components/Banner/style.scss
  src/pages/Main/components/HotSpaceCard/index.tsx
  src/pages/Main/components/HotSpaceCardList/index.tsx
  src/pages/Main/components/SearchBar/index.tsx
  src/pages/Main/components/SearchBar/style.scss
  src/pages/Main/components/SpaceCard/index.tsx
  src/pages/Main/components/SpaceCard/style.scss
  src/pages/Main/components/SpaceCardList/index.tsx
  src/pages/Main/components/SpaceCardList/style.scss
  src/pages/Main/index.tsx
  src/pages/MyReservation/components/CanceledModal/index.tsx
  src/pages/MyReservation/components/CanceledModal/style.scss
  src/pages/MyReservation/components/MyReservationCard/index.tsx
  src/pages/MyReservation/components/MyReservationCard/style.scss
  src/pages/MyReservation/components/MyReviewModal/index.tsx
  src/pages/MyReservation/components/MyReviewModal/style.scss
  src/pages/MyReservation/index.tsx
  src/pages/MySpaceManagement/components/MySpaceCard/style.scss
Labels: 메인 페이지, 공통 컴포넌트
